#! /usr/bin/env python3
'''this scripts batch preprocess the images, it runs pre_process.py for each image in the image_dir'''
'''and write the output in the images_output_dir'''
'''the input images in the image_dir are expected to be in the format of nii'''
'''the input images are in two layers folder in the following format '''
'''image_dir/subject_id/scan_id/scan_id_Hires.nii'''
'''the output image are going to be saved in the images_output_dir in a flat structure'''
'''images_output_dir/scan_id_Hires_preprocessed.nii'''

'''write a python script to do this'''

''' SCRIPT MOSTLY GENERATED BY CURSOR AND CLAUDE SONNET PLEASE USE WITH CAUTION'''
import os
import json
from pathlib import Path
import SimpleITK as sitk
import numpy as np

def load_config(config_path):
    with open(config_path, 'r') as f:
        return json.load(f)

def resize_image(image, target_shape):
    """Resizes the 3D image to the target shape using SimpleITK."""
    original_size = np.array(image.GetSize())
    target_size = np.array(target_shape)
    resize_factor = target_size / original_size
    resampler = sitk.ResampleImageFilter()
    resampler.SetSize([int(sz) for sz in target_size])
    resampler.SetOutputSpacing(image.GetSpacing() / resize_factor)
    resampler.SetInterpolator(sitk.sitkLinear)
    resampler.SetOutputDirection(image.GetDirection())
    resampler.SetOutputOrigin(image.GetOrigin())
    return resampler.Execute(image)

def normalize_image(image, brain_mask=None):
    """Normalizes voxel values to [0, 1] using min-max normalization."""
    image_array = sitk.GetArrayFromImage(image)
    if brain_mask is not None:
        mask_array = sitk.GetArrayFromImage(brain_mask)
        brain_voxels = image_array[mask_array > 0]
    else:
        brain_voxels = image_array

    # Calculate the 99th percentile value for normalization
    max_val = np.percentile(brain_voxels, 99)
    min_val = np.min(brain_voxels)

    # Clip values to avoid hot spots and scale to [0, 1]
    normalized_array = np.clip((image_array - min_val) / (max_val - min_val), 0, 1)

    return sitk.GetImageFromArray(normalized_array)

def center_brain(image, brain_mask=None):
    """Centers the brain within the image using the brain mask if available."""
    image_array = sitk.GetArrayFromImage(image)
    if brain_mask is not None:
        mask_array = sitk.GetArrayFromImage(brain_mask)
        brain_indices = np.array(np.nonzero(mask_array))
    else:
        brain_indices = np.array(np.nonzero(image_array))

    brain_center = np.mean(brain_indices, axis=1).astype(int)
    image_center = np.array(image_array.shape) // 2

    # Compute shifts needed to center the brain
    shifts = image_center - brain_center

    # Apply shifts using numpy roll
    centered_array = np.roll(image_array, shifts, axis=(0, 1, 2))

    return sitk.GetImageFromArray(centered_array)

def process_nifti_image(input_path, output_path, target_shape=(160, 214, 176), apply_brain_mask=True):
    # Load the NIfTI image using SimpleITK
    nifti_img = sitk.ReadImage(input_path)

   

    # Resize the image to target shape
    resized_image = resize_image(nifti_img, target_shape)

    # Normalize voxel values
    normalized_image = normalize_image(resized_image)

    # Center the brain within the image
    centered_image = center_brain(normalized_image)

    # Set metadata (direction, spacing, origin) from the original image
    centered_image.SetDirection(nifti_img.GetDirection())
    centered_image.SetSpacing([1.0, 1.0, 1.0])  # Set isotropic spacing (1mm³)
    centered_image.SetOrigin(nifti_img.GetOrigin())

    # Save the processed image
    sitk.WriteImage(centered_image, output_path)
def main():
    config = load_config('preprocessing/config.json')
    image_dir = Path(config['image_dir'])
    output_dir = Path(config['images_output_dir'])
    output_prefix = config['output_image_prefix']
    verbose = config['verbose']

    output_dir.mkdir(parents=True, exist_ok=True)

    for subject_dir in image_dir.iterdir():
        if subject_dir.is_dir():
            for scan_dir in subject_dir.iterdir():
                if scan_dir.is_dir():
                    input_file = next(scan_dir.glob('*_Hires.nii'), None)
                    if input_file:
                        output_file = output_dir / f"{scan_dir.name}_{output_prefix}.nii"
                        process_nifti_image(input_file, output_file)
                        if verbose:
                            print(f"Preprocessed: {input_file} -> {output_file}")

if __name__ == "__main__":
    main()










